spring.application.name=RabbitMail

spring.datasource.url=jdbc:mysql://localhost:3307/RabbitMailDB?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=America/Sao_Paulo
spring.datasource.username=myuser
spring.datasource.password=secret
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=myuser
spring.rabbitmq.password=secret

rabbitmail.rabbitmq.queue=email.queue
rabbitmail.rabbitmq.exchange=email.exchange
rabbitmail.rabbitmq.routing-key=email.routing.key

spring.mail.host=smtp.ethereal.email
spring.mail.port=587
spring.mail.username=taurean.dibbert@ethereal.email
spring.mail.password=AXXaYBWUb2dNqtzebp
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

rabbitmail.mail.simulation-enabled=true

server.port=8080
